name: Validate & Build Site

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  validate-build-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages                     
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate registry
        run: python scripts/validate.py

      - name: Generate docs
        run: python scripts/generate_site.py

      - name: Build MkDocs
        run: mkdocs build --strict

      - name: Setup Pages
        uses: actions/configure-pages@v5      

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

      - name: Deploy to GitHub Pages
        id: deployment                        
        if: github.ref == 'refs/heads/main'
        uses: actions/deploy-pages@v4
